### ISSUE TITLE
NameError: name 'op' is not defined

### ISSUE THREAD

**Issue by brothermechanic** [nutti/Magic-UV#87] opened 2018-05-02 08:59 UTC
Issue in version 5.1
Modules Installed (uv_magic_uv) from '/media/disk/uv_magic_uv.zip' into '/home/bm/.config/blender/2.79/scripts/addons'
Traceback (most recent call last):
  File "/usr/share/blender/2.79/scripts/modules/addon_utils.py", line 317, in enable
    importlib.reload(mod)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/bm/.config/blender/2.79/scripts/addons/uv_magic_uv/__init__.py", line 45, in <module>
    importlib.reload(op)
NameError: name 'op' is not defined

**Comment by nutti** [comment] 2018-05-06 12:00
Thanks for your report.

Sorry, I can't reproduce this error.
Can you show me the full operation for reproducing this error.

**Comment by schroef** [comment] 2018-05-06 19:01
I dont have this issue neither. He's probably missing the folder OP. Perhaps reinstall the addon and see if that fixes the issue.

This how 1 level of folders should look like.
![screen shot 2018-05-06 at 3 01 23 pm](https://user-images.githubusercontent.com/6923008/39676803-69f251b0-513e-11e8-82f1-a0aac90401f3.png)

**Comment by nutti** [comment] 2018-05-20 13:08
@brothermechanic 

Hi,
Is this problem resolved?

**Comment by nutti** [comment] 2018-05-28 02:43
@brothermechanic 

For now, I will close this issue.
If you still have any issues, feel free to reopen.

**Closed by nutti** 2018-05-28 02:43 UTC
