### ISSUE TITLE
UV pack ext. makes island for every face, rotates/distorts 

### ISSUE THREAD

**Issue by NolanGrant1** [nutti/Magic-UV#99] opened 2018-07-20 05:03 UTC
Hey Nutti, big thanks for making this addon, 
when I try to use the UV pack extension, at first it appears to work in the UV window, but on closer inspection, although the verts are properly welding between the two islands being stacked, one of the islands ( in this case those at the top) has had each of its faces made into a separate island, and those faces/islands are rotated (seemingly 90 degrees each subsequent face) and stetched to fit.
see attached images:
![setup](https://user-images.githubusercontent.com/41460773/42983868-32650536-8bb7-11e8-8d05-9fcfa26d2c49.jpg)
I've set up the the islands in question to start already overlapped, and with welded verts
![resultofpackextension](https://user-images.githubusercontent.com/41460773/42983870-36d894de-8bb7-11e8-95f3-cafc7515227f.jpg)
when unpacking, this happens (note how the uvs on the top are rotated and stretched)
![facesareindividualislands](https://user-images.githubusercontent.com/41460773/42983871-39978a9a-8bb7-11e8-9378-d31775e38c88.jpg)
this just shows the islands a bit more clearly.

the intention is to use the pack extension for video game assets that need really efficient unwraps. on top of messing up the way the textures display, this also means its harder to select islands, and the additional uv seams will increase my in game vert count

I also believe the copy uvs tool did something like this but I can't remember.

*edit* I tried this in the 5.1 update of magic UV and it still shows this behavior

Also, as an added feature request, if there could be an option to have the stacked (integrated) islands all moved outside the 0-1 uv space, except for 1 copy, this would make setting up UVs for baking in substance painter/designer much faster, as stacked islands will cause baking artifacts, but islands exactly 1 tile away will receive the same texture info while being ignored by the baker :)

![0to1spacefeature](https://user-images.githubusercontent.com/41460773/42984031-5c9ebd8c-8bb8-11e8-8339-70c2e316c788.jpg)

anyways thanks very much, and I apologize if I'm missing something easy

**Comment by schroef** [comment] 2018-07-21 19:37
I think that rotation i issue is something done by Blender it self. I always and keep wondering why objects get that 90deg rotation when being unwrapped. It has something to do with its location from the center of the scene. I cant remember it correct though.

There is this addon Align & Distribute, this has an option to rotate all islands according to one active face selected. Its quite nice, but sometimes also stretches the islands.

That other option seems very useful indeed using island tiles. Wouldnt be that hard to implement i guess :)

**Comment by NolanGrant** [comment] 2018-08-24 19:48
@nutti  

> Can you review after my implementation?

Sure, I'd love to.

do you think the issue with the pack integrated causing faces to rotate and distort and become islands is a bug, or the result of something that I am doing wrong?

**Comment by nutti** [comment] 2018-08-25 01:02
@NolanGrant 

> do you think the issue with the pack integrated causing faces to rotate and distort and become islands is a bug, or the result of something that I am doing wrong?

As @schroef wrote, this may a problem caused by blender itself.
This extension only overlaps UV island after UV packing, so it will unexpected results if you have a same problem when you use Pack UV feature in Blender.
Is the same result if you use Pack UV in Blender itself.

**Comment by NolanGrant** [comment] 2018-08-25 03:42
@nutti I just checked again and it doesn't look like it's coming from blender, when I pack using blender's built-in tool it moves the overlapped islands so that nothing overlaps, but the islands are never split up any further than they already were or rotated, so I think that is coming from the addon. I made another example to show you:

prepared model unwrapped. I've hidden the edges and faces to make it easier to see the texture.
![1](https://user-images.githubusercontent.com/41460773/44614598-cc3a5080-a7f5-11e8-8b86-20a194dd7cd7.jpg)

selected the island I will overlap
![2](https://user-images.githubusercontent.com/41460773/44614599-cc3a5080-a7f5-11e8-8593-f2b74ff9fe3f.jpg)

overlapped the island onto the symmetrical island to the left, this works fine but now I'd like to pack this without messing up the islands
![3](https://user-images.githubusercontent.com/41460773/44614600-cc3a5080-a7f5-11e8-9f85-41927b3a93c1.jpg)

when I use the pack extension from the add on, the islands stay overlapped, as desired, but the faces have all been made into separate islands, some rotated, and then placed beside each other to look like the original island. Look how in the 3d viewport the texture is no longer the same on the left as it is on the right like before. even though the vertices all overlap properly, the verts that are overlapping are not the correct ones
![4](https://user-images.githubusercontent.com/41460773/44614601-cc3a5080-a7f5-11e8-94b9-3bb81529f051.jpg)

this shows what happens if I then try to pack using blender's built in packer, showing how the faces have all become islands. You cant see it well here, but some of those long rectangles were scaled to way down in the x and way up in the y then rotated.
![5](https://user-images.githubusercontent.com/41460773/44614602-cc3a5080-a7f5-11e8-8329-458506ae63a3.jpg)

lastly, this shows what happend when I undid everything back to the beginning and did a regular built-in pack. The island on the right is still one continuous island and none of the faces have been rotated, scaled, or reordered, so I'm not sure that it's the regular built-in packer causing it. 
![6](https://user-images.githubusercontent.com/41460773/44614603-cc3a5080-a7f5-11e8-85ef-dfbd29d2602b.jpg)

**Comment by nutti** [comment] 2018-08-25 06:35
@NolanGrant 

Thanks for reply.
Technically speaking, this add-on uses **Pack UV** feature internally, and overlapped UV which is already packed.
So, this problem is occurred if **Pack UV** changes UV coordinates.
Your request is that this extension should be overlapped island without **Pack UV** again, don't you?

I have some question about your operation too.

> overlapped the island onto the symmetrical island to the left, this works fine but now I'd like to pack this without messing up the islands

Is this your operation?

> when I use the pack extension from the add on, the islands stay overlapped, as desired, but the faces have all been made into separate islands, some rotated, and then placed beside each other to look like the original island. 

Internally, this extension calls the **Pack UV**.
Is the option below the Tool-Shelf same among Blender's Pack UV and this extension?

Thanks.

**Comment by NolanGrant** [comment] 2018-08-25 06:59
@nutti  So essentially what I do is line up everything that I want to overlap (which creates a lot of empty spaces on more complex mesh) and then try to pack using the addon, which packs everything but causes the errors. If I use blenders pack there are no errors, but everything that was overlapped gets spread back out.

**Comment by nutti** [comment] 2018-08-26 01:54
@NolanGrant 

OK,
All you want to do is overlapping same island, don't you.
Pack UV (Extension) applies **Pack UV** again, so the UV will be changed, so I think this feature should be provided separated feature.

What do you think?

**Comment by NolanGrant** [comment] 2018-08-26 02:34
> All you want to do is overlapping same island, don't you?
yes, The end goal is to have islands that are overlapped to stay overlapped when the UV's are packed (this is what the pack extension is supposed to do right? pack islands while keeping similar ones layered?) 

> so the UV will be changed, so I think this feature should be provided separated feature.
I'm not sure if I understand this correctly, if the pack extension does what I think it does than this is already a separate feature, if you're talking about the "move overlapped islands +1 unit in the x axis so that they're outisde of the 0 to 1 UV space" feature I suggested, then yes, I agree that should be a separate feature.

The main thing I'm worried about though is why the UV faces get distorted and rotated when I use the pack extension from your addon, which seems to work aside from that, as when I do a regular pack I do not get these errors. 

Sorry if I'm just missing something simple, and thanks for taking the time to respond to all my comments

**Comment by nutti** [comment] 2018-08-28 12:17
@NolanGrant 

Hi,

I added two option to realize your request.

**Stride:** It enables to stride UV coordinates whose overlapped UV. I think that value **1.0** fits your purpose.

**Apply Pack UV:** If this option is off, this feature only changes the UV coordinates without using Pack UV feature in Blender itself. I think that value **off** fits your purpose.

![magic_uv_issue99](https://user-images.githubusercontent.com/1463952/44722160-2fcec180-ab07-11e8-8913-88eefc07ea55.png)

Can you review this?

https://github.com/nutti/Magic-UV/archive/issue_99.zip

**Comment by NolanGrant** [comment] 2018-08-31 02:31
@nutti  I've tried looking at it, but I'm having some problems, I think I might be installing the addon wrong. First I tried going through the install addon menu and clicking the zip "Magic-UV-issue_99" as-is,
then I tried to unzip the "Magic-UV-issue_99" file, zip the contained file "uv_magic_uv" which allowed the addon on to appear in my lists of addons to enable. When I enabled it I got an error,
![magic uv error 1](https://user-images.githubusercontent.com/41460773/44889544-49594000-aca4-11e8-97f0-cc60c2c24b1b.jpg)

I'm pretty sure I'm just installing it incorrectly or am missing some supporting software, sorry, I haven't found the time to start learning python yet.

**Comment by nutti** [comment] 2018-08-31 11:29
@NolanGrant 

Sorry, I forgot the install instruction.
Please check it from below link.

https://github.com/nutti/Magic-UV/wiki/Installation

Thanks

**Comment by NolanGrant** [comment] 2018-09-02 22:42
@nutti, my bad, I should have known to do that, anyways

the stride feature works great! but, the same issue still happens with packing. I can't just turn the "apply pack" checkbox you added off because I still need to pack the UV's once I've overlapped everything that needs to be overlapped. Sorry if I'm bad at explaining this,

1 So I make a game model and unwrap everything. 

2 To make my unwrap more efficient, I can overlap identical UV islands that can't be seen on the mesh at the same time (for example, front and back of many object can't both be seen at the same time, so reusing the same part of the texture is fine)

3 because I just moved an island on top of another island, there is now a hole where the first island was, so this area of the texture is wasted. I want to fill the hole by using the pack extension to scale/move/rotate all the islands to fill up that space.

4 if I use blender's pack, the islands I stacked before will unstack, which undoes my work, so I can't do this.

5 if I use pack extension with your add on (and apply pack on new version) it keeps the stacked islands together and packs the uv to use up all the space, which is great, and then the stride option moves the stacked islands out of the 0-1 uv space, which is also great,
but then there's a problem, when I look closer the islands that were overlapped and moved out of the bounds have been split into individual faces and distorted, so I can't use this because now that mirrored area will have incorrect textures and create lots of extra vert splits in engine.

the weird part is, when I use the regular pack, it never splits the islands into individual faces, and your add-on sometimes won't either when working on really simple meshes, but often will create the distortion, even though it's supposed to be using the same pack code as blender.

also, when I use the new pack, I don't get the "rotate" checkbox or "margin" slider in the operator, which is very important for padding

I can try to make a video or screencapture of the problem if it might help explain better.

sorry for the late reply, thanks again for all your help

**Comment by nutti** [comment] 2018-09-03 11:43
At first, I would like to check if the **stride** option meets your request.

Secondary, I would like to check your requirement at latter part.

> the weird part is, when I use the regular pack, it never splits the islands into individual faces, and your add-on sometimes won't either when working on really simple meshes, but often will create the distortion, even though it's supposed to be using the same pack code as blender.

Magic UV uses Pack UV feature in Blender itself.
So, the result depends on the Pack UV feature.
I think your problem is that Blender's Pack UV unpacks if you manually overlap UV.
Is this right?

> I want to fill the hole by using the pack extension to scale/move/rotate all the islands to fill up that space.

Your requirement is Pack UV should see scaled/moved/rotated island as same island, isn't it?

> also, when I use the new pack, I don't get the "rotate" checkbox or "margin" slider in the operator, which is very important for padding

I think this option will be displayed on the Tool Shelf on View3D.
However, I think this is not good UI, so I will revise add-on to show this option from the UV/Image Editor.

**Comment by NolanGrant** [comment] 2018-09-03 12:31
@nutti I didn't notice it at first, but stride actually cause the same (or similar) errors, even with apply pack turned off. 

(note that these are just to show the problem, I wouldn't use this for a mesh this simple), 
![setup](https://user-images.githubusercontent.com/41460773/44986691-9feba600-af52-11e8-8c26-70877d442162.png)

Even just using stride = 1, not using pack, issue still appears (I remember issue also happened before when trying to use copy uv's or another magic-uv feature) so I think it's the addon, not blender's pack.
see how the gradient on the right side isn't continuous?
the faces have been split from each other and flipped upside down in the UVS, so have several other faces (looks like every second face in the strip)
![stride operation results error](https://user-images.githubusercontent.com/41460773/44986693-a2e69680-af52-11e8-92da-0c847060282a.png)

this just shows that I can now pull the faces apart
![separate faces](https://user-images.githubusercontent.com/41460773/44987005-aa5a6f80-af53-11e8-81ca-da86219a4b09.png)

**Comment by nutti** [comment] 2018-09-03 14:09
Thanks for your great information.
Now I understand the problem more clearly.

> Even just using stride = 1, not using pack, issue still appears (I remember issue also happened before when trying to use copy uv's or another magic-uv feature) so I think it's the addon, not blender's pack.

Sorry, this is another issue which potentially exists on **Copy/Paste UV** feature.

> and this shows that the operator settings are missing

It looks strange. I did not notice it.
I will check soon.

> the faces have been split from each other and flipped upside down in the UVS, so have several other faces (looks like every second face in the strip)

Umm...
Is it same result if you stride is 0?
It's must be a strange result. But I can understand the problem you encountered.

**Comment by NolanGrant** [comment] 2018-09-03 14:13
@nutti I just checked, stride 0 also causes the error to occur

**Comment by nutti** [comment] 2018-09-05 10:44
@NolanGrant 

Thanks.
I got the situation.

**Comment by nutti** [comment] 2018-09-05 10:53
@NolanGrant 

> the faces have been split from each other and flipped upside down in the UVS, so have several other faces (looks like every second face in the strip)

BTW, I can not reproduce your error situation.
Can you send me a .blend file?

Other 2 issues are reproduced correctly.

**Comment by nutti** [comment] 2018-09-05 10:58
I wrote task list here because there are more than 2 problems reported.
@NolanGrant  If you have another error, I'm very appreciate to make another issue next time. It is very difficult to manage issue list. But thanks for reporting the issues, I didn't recognize them before.

- [ ] (Pack UV) Options in Tool-Shelf are missing
- [ ] (Copy/Paste UV) Exception is raised when the menu is opened
- [ ] (Pack UV) Each UV is separated after the operation

**Comment by nutti** [comment] 2018-09-05 13:39
Don't worry about it and thanks for many great feedback :-)

> here's a link to the blend file I used in the last explanation, it should have the gradient image packed, and is set up so that you should just be able to press the "pack UV" button in the UV editor window toolbar in order to trigger the error on the right side of the mesh

Thanks so much, I will try it.

**Comment by nutti** [comment] 2018-09-10 12:17
> (Copy/Paste UV) Exception is raised when the menu is opened

I fixed this bugs.
It's now in develop branch.

**Comment by nutti** [comment] 2018-09-10 12:33
> (Pack UV) Options in Tool-Shelf are missing

I also fixed this bugs.

**Comment by nutti** [comment] 2018-09-12 12:58
@NolanGrant 

I checked below issue from your .blend file.

> (Pack UV) Each UV is separated after the operation

It seems that this issue related to the other issue #80 .
UV topology is corrupsed by copy/paste island.
If you have the time please check issue #80 .

Now, I will tackle this problem.

Thanks

**Comment by NolanGrant** [comment] 2018-09-12 18:40
@nutti Thanks for tackling this, very excited to see it worked out

**Comment by nutti** [comment] 2018-09-15 00:38
@NolanGrant 

I searched the solution about this, and unfortunately I found that it takes lots of time for this computation.
It will be reasonable time if you only have ~100 UV coordinates, but it will not applicable to more verticies.

Here, this is a technically problem.
https://en.wikipedia.org/wiki/Graph_isomorphism_problem
https://en.wikipedia.org/wiki/Subgraph_isomorphism_problem

I will try to tackle from other side, but I could not say this problem is solved.

**Comment by areeseofcake** [comment] 2020-11-13 23:16
Heck I am running into this issue. No solution on the horizon right now?
![image](https://user-images.githubusercontent.com/74338049/99129719-f98c9800-25d3-11eb-872e-748439df742d.png)
![image](https://user-images.githubusercontent.com/74338049/99129731-fe514c00-25d3-11eb-8a9b-cdff55949e02.png)

**Comment by nutti** [comment] 2021-04-30 08:49
This bug is now fixed by using the same algorithm in Copy/Paste UV Island.

**Closed by nutti** 2021-04-30 08:49 UTC
Labels: bug
