### ISSUE TITLE
Texture UV Lock heavily warping.

### ISSUE THREAD

**Issue by Aquaowolf** [nutti/Magic-UV#118] opened 2019-11-15 23:51 UTC
**System Information**
  
* OS: Windows 10
* Blender version: 2.8
* Add-on version: 6.2

**Expected behavior**  
I should be able to move verts, edges, etc... and the texture stays in it's place un-warped.

**Description about the bug**  
When I start going everything's fine, I've used this addon alot lately for making foliage cards
so I make my plane, cut out around my texture, and once I subdivide or connect vertex paths
it's suddenly warping the whole texture, either stretching it super far or offsetting it.
When I look at my UV's and do it it begins taking the verts and slowly pulling them across the screen. And this was working perfectly fine yesterday mind you when I was working with version 6.0, I switched to 6.2 after looking into it and I get the same issue.

**Screenshots/Files** [Optional]  
*It is good to solve the bug if you attach the screenshots or .blend file.*
![image](https://user-images.githubusercontent.com/57817295/68983417-7b36c380-07d0-11ea-9c6a-a53096d38d67.png)
The moment I select a vert
![image](https://user-images.githubusercontent.com/57817295/68983440-8d186680-07d0-11ea-850b-ffc846b3641d.png)

**Additional comments** [Optional]

**Comment by Ronald-MannMade** [comment] 2021-02-11 16:55
this seems to still be happening with addon version 6.4 , Blender 2.9.2

**Comment by DORKINHORKIN** [comment] 2022-09-26 23:17
I can confirm this issue is still present in Blender 3.3.0
![image](https://user-images.githubusercontent.com/34221540/192397266-3c91b6c7-6a89-4367-8fc4-0526a4594e71.png)

**Comment by EugeneDudavkin** [comment] 2023-03-19 09:27
My workaround since 2019 is use edge slide (G+G) or freemove slide (G+G+G) but need to be in some aligned view to prevent 3rd axis move.

**Comment by EugeneDudavkin** [comment] 2023-03-22 07:00
Implemented in Blender
https://projects.blender.org/blender/blender/issues/78416

**Comment by nutti** [comment] 2023-03-22 09:54
Close this issue (See: https://github.com/nutti/Magic-UV/issues/95#issuecomment-1479240537)

**Closed by nutti** 2023-03-22 09:54 UTC
Labels: wontfix
