### ISSUE TITLE
Offset uv faces to -1.0, 1.0 uv range

### ISSUE THREAD

**Issue by DusanStev** [nutti/Magic-UV#113] opened 2019-08-01 22:12 UTC
Hi, 

I am attaching working script (works in Blender 2.80). Made it for myself, but it would be great if you could use it/modify it, and put it in the Magic-UV as standard option.

I use it to move UV faces to -1.0, 1.0f UV range, since on mobile graphic hardware there are issues with UV precision when large numbers are used. With this add-on, UV faces (centers) are moved closely as possible to center 0.0f, with preserved tiling (for test use box or smart unwrap, scale it to be larger than image in UV editor and select "DS offset move faces" from unwrap menu in edit mode). 

With this add-on it is possible to preserve tile mapping of detail textures (grass, stones, metal 
etc.) on large game level meshes (which were initially mapped with some other automatic option) and have UV coordinates moved to acceptable UV range for mobile devices.
[uv_offset_move_faces2.zip](https://github.com/nutti/Magic-UV/files/3458820/uv_offset_move_faces2.zip)

![uv01](https://user-images.githubusercontent.com/35195007/62330859-3c4b5f00-b4ba-11e9-9faf-472ebd5f53f5.PNG)
![uv02](https://user-images.githubusercontent.com/35195007/62330860-3f464f80-b4ba-11e9-9f83-a740f2851e0d.PNG)

**Comment by nutti** [comment] 2019-08-02 09:07
@DusanStev 

It looks nice to include this feature to Magic UV.

I think the feature already works fine.
If you want to try to include this feature by yourself, you can send pull request from below link.
https://github.com/nutti/Magic-UV/pulls

Are you willing to send pull request and merge this feature manually?
I'm waiting for your response.
Anyway, thanks for a feature request.

**Comment by DusanStev** [comment] 2019-08-02 16:05
@nutti

I am primarily C/C++/C# programmer, so python and blender API is something that I do in "emulation" :) mode (when I have to), prone to trial and error, and not so elegant as I wanted to. So, maybe it is a better solution, for you to properly insert this part of code somewhere in Magic UV when you find time (perhaps it would be better suited to be in UV editor as option to modify existing UV). 

Please use this code as you find fit, and thank you for developing really useful add-on.

**Comment by nutti** [comment] 2019-08-02 23:01
@DusanStev 

I understood your background.
Then, I will include your codes ASAP.
Thanks for your codes.

And I have a request about including your name to add-on's authors.
It is a rule of Blender's add-on to include developers name as add-on's authors.
If you have a proper name as add-on author, please tell me.

**Comment by DusanStev** [comment] 2019-08-03 04:53
Please use the name supplied in add-on author field (or if is too long use DusanStev). Thank you.

**Comment by nutti** [comment] 2019-08-06 00:20
@DusanStev 

I'm now trying to merge your feature.
And I have a question about this feature.

I tried to adopt this feature to simple box UV map, and I found that the UV island is collapsed.
Is it expected behavior because it looks same even if UV coordinate is differ?

**Comment by nutti** [comment] 2019-08-06 09:34
@DusanStev 

Added your feature as **Clip UV**.
Before I merge this feature to mainline of Magic UV, could you try this feature?
Some options (the range can be configured by the users) are added to this feature.

https://github.com/nutti/Magic-UV/archive/spike_113.zip

<img width="229" alt="github_20190806" src="https://user-images.githubusercontent.com/1463952/62528840-77fa7600-b878-11e9-8301-d3b4bd9a3fa5.png">

**Comment by DusanStev** [comment] 2019-08-07 13:57
Hi, i have tested it. Found some issues: 
1) I don't know if it is a glitch, but when i compare inserted feature with original script it does not return same result (visible on screenshots). I use min/max values set as on screenshot to try get the same behavior (maybe script default should be 0.5, -0.5 instead of 1.0, -1.0).  

2) script reports math domain error if both values for min/max are zero (maybe prevent user from doing that, override in code so that minimum allowed values are 0.5, -0.5. 

3) I seems that min/max values that are not dividable with 0.5 are breaking original tiling of texture. Eg. (0.5,-05)(1.0, -1.0)(1.5, -1.5) works fine, but (0.75, -0.75) (1.25, -1.25) etc. breaks tiling of original texture. So maybe allowed value step should be always 0.5.

Maybe limit what user can enter like putting step button which is  0 on start and increments always by one. That "step" value (0, 1, 2, 3...) than multiplies in python value of 0.5 for min max range (step+1) * 0.5 for max, or (step+1) * -0.5 for min allowed value.

Thank you for implementing it.

![uv_magic](https://user-images.githubusercontent.com/35195007/62628511-bdc44680-b92b-11e9-9859-d3c2313b6e63.PNG)
![uv_orig](https://user-images.githubusercontent.com/35195007/62628512-bdc44680-b92b-11e9-8049-9677440fae44.PNG)

**Comment by DusanStev** [comment] 2019-08-07 14:22
> @DusanStev
> 
> I'm now trying to merge your feature.
> And I have a question about this feature.
> 
> I tried to adopt this feature to simple box UV map, and I found that the UV island is collapsed.
> Is it expected behavior because it looks same even if UV coordinate is differ?

Sorry missed this in reply. Yes it is intended, sometimes UV island can be very large, and it has to split in individual faces to fit (maybe use check box, split islands on/off).

**Comment by nutti** [comment] 2019-09-17 05:22
@DusanStev 

Sorry for the late reply.
I understand your intention. Thanks.
I will tackle this feature ASAP after I finished other works.

**Comment by nutti** [comment] 2019-09-17 12:19
@DusanStev 

I fixed the issues you mentioned.
Could you try this new version from below link?

https://github.com/nutti/Magic-UV/archive/spike_113.zip

Thanks.

**Comment by DusanStev** [comment] 2019-09-22 12:42
Thank you for update. I have tested it today (sorry for delay). It uses 0.5 range for input and preserves tiling, but it seems that result is always the same, regardless of values used in min/max field of Clip UV.

**Comment by nutti** [comment] 2019-09-25 11:26
> It uses 0.5 range for input and preserves tiling, but it seems that result is always the same, regardless of values used in min/max field of Clip UV.

Thanks.
Umm.., it looks strange.
I will check it.

**Comment by nutti** [comment] 2019-09-30 12:35
@DusanStev 

> It uses 0.5 range for input and preserves tiling, but it seems that result is always the same, regardless of values used in min/max field of Clip UV.

I found the cause of this bug.
This bug is now fixed.
You can try bug fixed version from below link.

https://github.com/nutti/Magic-UV/archive/spike_113.zip

**Comment by DusanStev** [comment] 2019-10-02 17:17
It is working now :). I've tested it a bit and everything seems fine. There is a small difference in result compared to original script... but this one has adjustable clipping :). 

Thank you

**Comment by nutti** [comment] 2019-10-03 10:54
Thanks for checking this feature.
Now it is merged into develop branch, and will be released next version (v6.3).

**Closed by nutti** 2019-10-03 10:54 UTC
Labels: enhancement
