### ISSUE TITLE
[5.1.0] Tranfer UV - Warning "Face have different amount of Faces"

### ISSUE THREAD

**Issue by schroef** [nutti/Magic-UV#92] opened 2018-06-01 19:21 UTC
rv 5.1.0
bl 2.79b

Im trying my luck again with the Transfer UV, i had some issues in the past with this thing. Now i got a new one. I select to faces (4 verts), U > Transfer UVs > Copy  Than i select the other 2 faces, U > Transfer UVs > Paste then i get this warning;
`Face have different amount of vertices`
![screen shot 2018-06-01 at 3 07 40 pm](https://user-images.githubusercontent.com/6923008/40859298-43a3fb96-65af-11e8-8bd4-4a0fbb867fe7.png)

Here's a small screengrab
![trasnfer-uvs-faces-warning](https://user-images.githubusercontent.com/6923008/40859273-3641c06e-65af-11e8-8a70-c1ea240afbe9.gif)

Transfer UV is for forcing the uvs to be transferred, no matter if they dont have same amount of verts or faces, right?  Perhaps im confussed now, i believe i used it like this in the past. I know there have been some issues with. Im am transferring UV within the same mesh, i believe the other option for transferring them between different objects was a to do.

**Comment by nutti** [comment] 2018-06-02 01:19
@mifth 

Is there any comment about this issue?
I think that this issue raised from the difference of the topology.
And I also think this is a default behavior.

**Comment by schroef** [comment] 2018-06-02 07:04
What is the usage then for transfer? Wasnt there a option to force uv transfer to a different mesh part?

**Comment by nutti** [comment] 2018-06-02 07:17
@schroef 

Copying and Pasting meshes must have SAME topology.
The error you showed, is raised because you have different topology in your mesh.
I can infer that your copied/pasted meshes are different topology from your video.
This is a different from copy/paste UVs.

**Comment by schroef** [comment] 2018-06-02 07:20
Perhaps im not getting the point but doesnt my error show the same issue when not have the same topolgy. Tranfer UV is for transferring between mesh which dont have the same abount of vets, faces and thus topology? Otherwise i dont understand its usage, i cant seem to find proper documentation what it really doest. There is only workflow and updates info about it, no documentation

**Comment by mifth** [comment] 2018-06-02 07:27
Hi guys!
Sorry i have just noticed this issue.
@schroef could you please give us the blend file with the issue.
I guess this is topology difference as @nutti said.

**Comment by schroef** [comment] 2018-06-02 20:03
Here's the mesh i was doing, hope it helps

http://www.filedropper.com/transfer-issue

**Comment by mifth** [comment] 2018-06-04 09:04
It's impossible to copy UVs. The prts have different ammount of faces and they have different topology.

![image](https://user-images.githubusercontent.com/2251298/40908385-43ed106e-67ef-11e8-8867-bdf7d359d065.png)

![image](https://user-images.githubusercontent.com/2251298/40908394-4f77ce38-67ef-11e8-9e12-e5dd1377d40b.png)

**Comment by nutti** [comment] 2018-06-04 12:17
I checked .blend file too.
I think this error is raised because of the difference of topology as @mifth said.
And I also find that some face consists of the different number of the vertices.

@schroef 

You can check the usage and the background which Transfer UV is developed from #11 .
Transfer UV is a feature that exists in Modo 901.

This issue is not a bug, so I will close this issue for now.

@mifth 
Thanks for checking this issue.

**Closed by nutti** 2018-06-04 12:17 UTC

**Comment by schroef** [comment] 2018-06-05 00:56
Ahh i see, i was presuming this was a forced transfer.

Thanks for clearing this

**Comment by nutti** [comment] 2018-06-05 11:32
> I really dont understand why transfer is handy above copy/paste, C/p can do paste without same vert number. 

Copy/Paste UV sometimes fails to paste UV correctly because of the incorrect UV index.
Transfer UV solves this problem because this is a topological based copy/paste UV.
This is the difference between Copy/Paste UV and Transfer UV.
Also, Transfer UV can not solve the problem that copy/paste among meshes which does not have same topology.
It's a specification rather than a bug.

**Comment by schroef** [comment] 2018-06-05 23:35
Ah that clear it, i think its perhaps a good idea to add this info to the wiki part.
