### ISSUE TITLE
Straighten raises bug

### ISSUE THREAD

**Issue by AntonioCaroppos** [nutti/Magic-UV#117] opened 2019-11-10 18:43 UTC
**System Information**
  
Windows 10
Blender v 2.81 Beta
Magiv UV 6.2.0

UVs should be straightened
Blender reports errors

I have uploaded a video here:
https://youtu.be/6NSumPmhWjs

I have uploaded the Blend file here:
http://pasteall.org/blend/index.php?id=52580

**Comment by nutti** [comment] 2020-05-21 13:37
@AntonioCaroppos 

Sorry for very late reply.
This issue is duplicate of #119 , and already fixed.
I did not release the add-on with this patches, but you can try it from [unstable version](https://github.com/nutti/Magic-UV/archive/develop.zip).
If you have any other issues related this feature, please open the issue.
Thanks.

**Closed by nutti** 2020-05-21 13:37 UTC
Labels: duplicate
