### ISSUE TITLE
Weird bug when trying to measure scaling density

### ISSUE THREAD

**Issue by kingsushi001** [nutti/Magic-UV#145] opened 2021-01-12 20:12 UTC
**System Information**
  
* OS: Windows 10
* Blender version: 2.91.0
* Add-on version: 6.4.0

Hi

I am getting the following error when trying to measure the scaling density of a plane. I'm not sure why this is happening as I've used this specific feature dozens of times without any problems 

Error:
```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\addons\magic_uv\ui\view3d_uv_manipulation.py", line 173, in draw
    MUV_OT_WorldScaleUV_Measure.setup_argument(ops, sc)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\addons\magic_uv\op\world_scale_uv.py", line 379, in setup_argument
    ops.tgt_texture = scene.muv_world_scale_uv_measure_tgt_texture
TypeError: bpy_struct: item.attr = val: enum "" not found in ('[Average]', '[Max]', '[Min]', 'ref_25mm.png')

location: <unknown location>:-1
```

I will mess around some more and try to figure out why this is happening all of a sudden.

**Comment by nutti** [comment] 2021-02-03 08:07
@kingsushi001 

Sorry for late response.

I could not reproduce this error.
Is it possible to send me a .blend file which encounters this issue?

**Comment by nutti** [comment] 2021-02-05 08:16
I found that this error will be raised when the items of EnumProperty are deleted.
I have already applied the workarounds for this issue.
So, I will close this issue.

**Closed by nutti** 2021-02-05 08:16 UTC
Labels: bug
