### ISSUE TITLE
UV Overlapping issue.

### ISSUE THREAD

**Issue by mifth** [nutti/Magic-UV#146] opened 2021-03-04 09:50 UTC
Hi Nutty!

I have found one issue with overlapping. If UV is overlapped but also flipped it will not be considered as overlapped. I attached my blend file.
[tmp1.zip](https://github.com/nutti/Magic-UV/files/6082476/tmp1.zip)

![image](https://user-images.githubusercontent.com/2251298/109945195-0ef31280-7ce8-11eb-844c-0fd0a8a1ee38.png)
![image](https://user-images.githubusercontent.com/2251298/109945322-27fbc380-7ce8-11eb-8c2d-2a1df37b7021.png)

**Comment by nutti** [comment] 2021-03-05 08:23
Thanks.
But, I need a time to fix this because of the critical error on Blender 2.93.

**Comment by mifth** [comment] 2021-03-05 08:24
No worries. There is nu hurry.

**Comment by nutti** [comment] 2021-03-09 09:08
@mifth 

I'm now trying to find the reason, but I could not reproduce this with a simple case (one rect polygon is flipped, another rect polygon is not flipped).
Is there any simple case you encountered this issue?

**Comment by nutti** [comment] 2021-03-09 09:19
Perhaps, the issue comes from not flipping but rotation.
I can reproduce this issue by using rotated UV.

**Comment by nutti** [comment] 2021-03-10 08:28
I found this issue is raised when the UVs are in same islands.
Maybe, we can solve this issue by checking the overlapped UVs intra-UVisland as well as inter-UVisland.

**Comment by mifth** [comment] 2021-03-10 08:40
@nutty
Apologies for late reply. Here is my simple test. I attached my blend file.

[tmp1.zip](https://github.com/nutti/Magic-UV/files/6114428/tmp1.zip)

In this situation I suppose all these faces should be considered as overlapped.
![image](https://user-images.githubusercontent.com/2251298/110600735-515b9a00-8195-11eb-97b9-f4ce4e48e3b8.png)


I flipped only these faces:
![image](https://user-images.githubusercontent.com/2251298/110600881-794afd80-8195-11eb-82ac-56cf12844272.png)

**Comment by mifth** [comment] 2021-03-10 09:38
@nutty Thank you.
Thank you a lot! Works fine on this example.

I opened the first model and found some issues:
1)
Could I ask to increase default value?
![image](https://user-images.githubusercontent.com/2251298/110608489-5a506980-819d-11eb-85a5-d1f21958aeb7.png)
![image](https://user-images.githubusercontent.com/2251298/110608511-5e7c8700-819d-11eb-988d-31d6700f53a9.png)


2)
I have found this face was selected as overlap, but these is no overlaps.
![image](https://user-images.githubusercontent.com/2251298/110608685-87048100-819d-11eb-9e6f-5d7308155a03.png)

**Comment by nutti** [comment] 2021-03-10 12:53
@mifth 

> 1) Could I ask to increase default value?

Yeah, it is possible to increase default value.

> 2)

Hmm, it is difficult to fix this.
It seems a small computational error in below code.
https://github.com/nutti/Magic-UV/blob/156b0aac98191fde2c96f9dd2ed1bafc3f8ba39d/src/magic_uv/common.py#L1202-L1214
I use a ray casting algorithm in here.
https://en.wikipedia.org/wiki/Point_in_polygon
If the UV coordinates are same, point will be in the polygon.

**Comment by mifth** [comment] 2021-03-10 13:40
Aaa, understood.

What if to check if a polygon center is in UV Shell?
UV shells could be taken from bpy_extras.mesh_utils.mesh_linked_uv_islands(obj.data)
https://docs.blender.org/api/current/bpy_extras.mesh_utils.html?highlight=island#bpy_extras.mesh_utils.mesh_linked_uv_islands

![image](https://user-images.githubusercontent.com/2251298/110637950-048cb900-81bf-11eb-8a76-7dcd55bbf3c9.png)

**Comment by mifth** [comment] 2021-03-10 13:48
Or checking if a polygon center is a polygon?

**Comment by nutti** [comment] 2021-03-10 23:57
Thanks.
But I found another way (Only tweaking the current algorithm).

Maybe this works fine.
https://github.com/nutti/Magic-UV/archive/develop.zip

**Comment by mifth** [comment] 2021-03-12 08:15
@nutti  everything is perfect! Thank you a lot for your effort!

**Comment by nutti** [comment] 2021-03-13 00:17
Merged. Thanks for your cooperation @mifth .

**Closed by nutti** 2021-03-13 00:17 UTC
Labels: bug
